#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'colorscheme'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#javascript"
auto_fix = true
enable_flow_syntax = true
format_on_save = true

# [[layers]]
  # name = "'junegunn/rainbow_parentheses.vim'"
  # merged = false

# [[layers]]
   # name = "lang#typescript"
   # merged = false
#
# [[layers]]
  # name = "format"
  # merged = false
  # format_on_save = true
#
# [[layers]]
  # name = "gtags"
  # merged = false
  # gtagslabel = "pygments"
#
# [[layers]]
  # name = "checkers"
  # merged = false
#
# [[layers]]
  # name = "treesitter"
  # merged = false
#
# [[layers]]
  # name = "autocomplete"
  # merged = false
#
# [[layers]]
  # name = "lang#html"
  # merged = false
#
# [[layers]]
  # name = "lang#graphql"
  # merged = false
#
# [[layers]]
  # name = "shell"
  # merged = false
  # default_position = "bottom"
  # default_height = 20
#
# [[layers]]
  # name = "lsp"
  # enabled_clients = ['vimls', 'clangd', 'c', 'cpp', 'html', 'javascript', 'javascriptreact', 'objcpp', 'rust', 'vim', 'sh', 'typescript', 'typescriptreact']
  # merged = 0

# [[custom_plugins]]
  # name = "MaxMEllon/vim-jsx-pretty"
  # merged = false
#
# [[custom_plugins]]
 # repo = "https://github.com/peitalin/vim-jsx-typescript"
  # merged = false
#
# [[custom_plugins]]
 # repo = "https://github.com/ms-jpq/coq.thirdparty"
  # merged = false
#
# [[custom_plugins]]
 # repo = "https://github.com/ms-jpq/coq.artifacts"
  # merged = false
#
# [[custom_plugins]]
 # repo = "https://github.com/ms-jpq/coq_nvim"
  # merged = false
#
# [[custom_plugins]]
 # repo = "https://github.com/HerringtonDarkholme/yats.vim"
  # merged = false
#
# [[custom_plugins]]
 # repo = "https://github.com/prettier/vim-prettier"
  # merged = false
#
# [[custom_plugins]]
 # repo = "https://github.com/airblade/vim-gitgutter"
  # merged = false
#
# [[custom_plugins]]
 # repo = "https://github.com/github/copilot.vim"
  # merged = false
#
# [[custom_plugins]]
# repo = "https://github.com/sheerun/vim-polyglot"
  # merged = false
#
# [[custom_plugins]]
 # repo = "https://github.com/neovim/nvim-lspconfig"
#
# [[custom_plugins]]
   # repo = "https://github.com/justinmk/vim-sneak"
